language: node_js
node_js:
- node
- 6
deploy:
  api_key:
    secure: jq0KPgb1h5UvsulDXQdLDsfyPTJEfK6TSnL+u63ECshaUwNo0u3XtIiDFX2ZcropMmOmLmBnO5RR0OyCg9/Frop94BRg+qTgDXnsmGx8AfjYQmuI+zaNy98cHZqefGHzwwgE1OewVkrzIkNL7Ew13g4SOvO/xlhT9SVtU5QyV9ku9eabDogyAlm7HFWdVwD721qDpFm/EoS5cmiS/VosDMLByHEimvlV2E8FGYPs9lBCuvCaNiaMhYdYw2+aSNyLxtTbBgly1oFv742ZZM2uO+l5NYDCg3tVHMFv5oSnDS4dRafI+8R2FODLitXlxrEe2FdzIQA/YTyoy44QQVudgQZtXWjbG3y0cSnIZ5PrK1/4NNWgwuDHpfgMWFBskKE+cDwVaODy5WUbyuRWzGKdROHTpPcho7MQl+bI2S2zZgNwWw4zYRvPiOxmZFmDXuW3GtD7c+vT3lBkLIVdd/tqrzkPr6UEfSyaKA1RUfGMoip3fcMwgCuSp2pySadCsjdcBs9BnHgpoWNveSXPaPpumUfPnVnlxwrrExsD6DFyxf4ImQFuy7piUuO+gfC7ABN9rLoW6uEZNmM/sW7SLIK/oOgQt0bMPj4ly8r98o1UttW9SDqff5tbhiF81vRwYOBRPPVVzDP3gCrvRyj020r4jO5XlHNCIudbI9QQJpu9rQ8=
  email: al@builtbybrayne.com
  provider: npm
  on:
    tags: true
notifications:
  slack:
    secure: NPH5D0mhfvK7BoFnt/iS60rkrV7ru1O2BFPR3yNmJnlBbA6Tb1e4hIqusJu+G6Y87VtTq5kopefH3Hd7PierdCSjQ7lR1bpC0yaN7VMK3X0MBAALnTwanFcZyT4ymangiIZmwg1999aJ2A/0S7B7dRnLSztZ2gssQRBRknWMD8cXjLyL98IzyKZIlqc49nUN4+XjC9HWqfCusxkTQt2DVEQfS54ChQBsWMa3QPHxPjn4R+8CJffFATiBsmfzSg5av/Ke3yYt5/ocgZYl1EI8pmqQrou8OjVfgK1+9mLrXz70KVSOygcbo3lxLWmnP/pIo75IXamMjw5miwucLXyfjBt7xXRqG/upThIeRFBw2ZcpmUU2NrI7QECTvhG/ynMQxjf/qidqTbRLKUU/5Sau/BpRimvB+K8H1YnwTcdpqOZ3I6RRZip5aOVNMqR7KShNb+4WskhP/7X02PhgHR5+ZuJumuaqIFWPs9rb2U6ee9fvdd/Sf4CiL9xIXpfJQz2ZhXTP3zC0DHztUPQTpi6vOaFm2g1HSu/9DOmQNwj9SGLTEMIp14Fj0uB35maIGhtyL4GuWOPg/HhEd9dfwgznG3YAJ2gt6o6J60ZGfrfYAmPa93XNk/Y/Ol2pn5WGCScaWiO6kKgazah6HkKooJY+XjSHqu0PnEUH1ZQXfdIiLAI=
